Add check for RHELHALOC user key

diff --git a/SAPHana/SAPHana b/SAPHana/SAPHana
--- a/SAPHana/SAPHana
+++ b/SAPHana/SAPHana
@@ -167,8 +167,8 @@ The resource agent uses the following four interfaces provided by SAP:
 4. hdbsql / systemReplicationStatus
    Interface is SQL query into HANA (system replication table).  The hdbsql query will be replaced by a python script 
    "systemReplicationStatus.py" in SAP HANA SPS8 or 9.
-   As long as wee need to use hdbsql you need to setup secure store users for linux user root to be able to
-   access the SAP HANA database. You need to configure a secure store user key "SLEHALOC" which can connect the SAP
+   As long as we need to use hdbsql you need to setup secure store users for linux user root to be able to
+   access the SAP HANA database. You need to configure a secure store user key "SLEHALOC"/"RHELHALOC" which can connect the SAP
    HANA database: 
 
 5. saphostctrl
@@ -766,13 +766,25 @@ function analyze_hana_sync_status()
 {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
     local hana_sync_status="" what_does_the_chamelion_say=""
-    local secUser="slehaLoc"
     local rc=0
     local sqlrc=0
     local query_state='select distinct REPLICATION_STATUS from SYS.M_SERVICE_REPLICATION'
     local query_secondaries='select distinct  SECONDARY_HOST from SYS.M_SERVICE_REPLICATION'
     local query_failed_secondaries="select distinct SECONDARY_HOST from SYS.M_SERVICE_REPLICATION  where SECONDARY_SITE_NAME = (select distinct  SECONDARY_SITE_NAME from SYS.M_SERVICE_REPLICATION WHERE REPLICATION_STATUS != 'ACTIVE')"
     local all_cluster_hosts all_secondary_hosts all_broken_secondaries
+    # TODO: PRIO4: remove check_secstore_users later
+    check_secstore_users SLEHALOC; chkusr=$?
+    if [ $chkusr -ne 0 ]; then
+         check_secstore_users RHELHALOC; chkusr=$?
+         if [ $chkusr -ne 0 ]; then
+              super_ocf_log err  "ACT: Secure store users are missing (see best practice manual how to setup the users)"
+              rc=$OCF_ERR_CONFIGURED
+         else
+             secUser="RHELHALOC"
+         fi
+    else
+         secUser="SLEHALOC"
+    fi
     hana_sync_status=$(timeout 60 $DIR_EXECUTABLE/hdbsql -a -x -U $secUser  $query_state); sqlrc=$?
     hana_sync_status=$(echo $hana_sync_status | dequote)
     super_ocf_log debug "DBG: hdbsql rc=$sqlrc hana_sync_status=\"$hana_sync_status\""
@@ -1459,8 +1471,20 @@ function saphana_start_clone() {
     # TODO: PRIO4: remove check_secstore_users later
     check_secstore_users SLEHALOC; chkusr=$?
     if [ $chkusr -ne 0 ]; then
-         super_ocf_log err  "ACT: Secure store users are missing (see best practice manual how to setup the users)"
-         rc=$OCF_ERR_CONFIGURED
+         check_secstore_users RHELHALOC; chkusr=$?
+         if [ $chkusr -ne 0 ]; then
+              super_ocf_log err  "ACT: Secure store users are missing (see best practice manual how to setup the users)"
+              rc=$OCF_ERR_CONFIGURED
+         else
+             set_hana_attribute ${HOSTNAME} "DEMOTED" ${ATTR_NAME_HANA_CLONE_STATE[@]}
+             check_for_primary; primary_status=$?
+             if [ $primary_status -eq $HANA_STATE_PRIMARY ]; then
+                 saphana_start_primary; rc=$?
+             else
+                 saphana_start_secondary; rc=$?
+                 lpa_set_lpt  30
+             fi
+         fi
     else
         set_hana_attribute ${HOSTNAME} "DEMOTED" ${ATTR_NAME_HANA_CLONE_STATE[@]}
         check_for_primary; primary_status=$?
@@ -1939,7 +1963,6 @@ SAPCONTROL=""
 DIR_PROFILE=""
 SAPSTARTPROFILE=""
 SAPHanaFilter="${OCF_RESKEY_SAPHanaFilter:-ra-act-dec-lpa}"
-
 
 if [ $# -ne 1 ]
 then
